### ISSUE TITLE
Results count

### ISSUE THREAD

**Issue by usctzen** [irahorecka/pycraigslist#4]
Ira,

Is there a way we could get a result count before running the loop? Does not need an exact number. It just could be a False/True situation. I don't know where you would put this, but if the `has_results = True` you run the loop.

Not a deal-breaker, but it would be nice.

Thanks

**Comment by irahorecka** [comment]
Hey Marc, great idea. I just released the updated version. You can get post count using the ``.count`` attribute:

```python
import pycraigslist

seattle_apa = pycraigslist.housing.apa(site="seattle", max_price=800)
print(seattle_apa.count)

>>> 410
```

**Comment by usctzen** [comment]
You are fast. It seems to be working fine. Thanks again.

**Comment by irahorecka** [comment]
No problem, and thanks for your contributions.
